### ISSUE TITLE
Camera found, but the detector is proceeding as there is no camera.  

### ISSUE THREAD

**Issue by zamanashiq3** [AlexShkarin/pyLabLib-cam-control#4]
I have a Thorcam CS165CU | Color CMOS | 1/2.9" (6.2 mm Diagonal) | Global Shutter | 3.45 µm x 3.45 µm | 34.8 fps (Full Sensor) | <4.0 e- RMS. that i am trying to connect to the software. The detector seems to detect the camera but in the later part, it shows showing no camera found.

**Comment by AlexShkarin** [comment]
Hello!

It's hard to say what exactly is going on. I've never tested it with this particular camera, but it did work with a couple of different Thorlabs Kiralux cameras which use the same API.

Could you check if there are ``logout.txt`` and ``logerr.txt`` files in the inner ``cam-control`` folder (the one with a bunch of ``.py`` files) and if there are, send them here? Do get more details, it would also be good if you could run ``detect.exe`` with the ``--show-errors`` command line option and send the result here (it should also generally be in ``logout.txt`` and ``logerr.txt`` files).

**Comment by zamanashiq3** [comment]
Hi, this is the last run results:
Starting detect.py on 2023/10/04 at 12:53:46

Searching for Andor SDK2 cameras
Error loading or running the Andor SDK2 library: required software (Andor Solis) must be missing

Searching for Andor SDK3 cameras
Error loading or running the Andor SDK3 library: required software (Andor Solis) must be missing

Searching for Basler cameras
Error loading or running the Basler library: required software (Basler pylon) must be missing

Searching for IMAQ Bonito cameras
Error loading or running the IMAQ library: required software (NI Vision) must be missing

Searching for DCAM cameras
Error loading or running the DCAM library: required software (Hamamtsu HOKAWO or DCAM API) must be missing

Searching for IMAQdx cameras
Error loading or running the IMAQdx library: required software (NI IMAQdx) must be missing

Searching for PCO cameras
Error loading or running the PCO SC2 library: required software (PCO SDK) must be missing

Searching for PhotonFocus cameras (might take several minutes)
Error loading or running the PFCam library: required software (PhotonFocus PFRemote) must be missing

Searching for Thorlabs TSI cameras
Found 1 Thorlabs TLCam camera
Found Thorlabs TSI camera serial=08126
Searching for Picam cameras
Error loading or running the Picam library: required software (Princeton Instruments PICam) must be missing

Searching for Pvcam cameras
Error loading or running the Pvcam library: required software (Photometrics PVCAM) must be missing

Searching for Throlabs uc480 cameras
Found no uc480 cameras

Searching for IDS uEye cameras
Error loading or running ueye library: required software (IDS uEye) must be missing

Configuration file already exists. Modify? [y/N] Successfully generated config file settings.cfg

**Comment by zamanashiq3** [comment]
> Hello!
> 
> It's hard to say what exactly is going on. I've never tested it with this particular camera, but it did work with a couple of different Thorlabs Kiralux cameras which use the same API.
> 
> Could you check if there are `logout.txt` and `logerr.txt` files in the inner `cam-control` folder (the one with a bunch of `.py` files) and if there are, send them here? Do get more details, it would also be good if you could run `detect.exe` with the `--show-errors` command line option and send the result here (it should also generally be in `logout.txt` and `logerr.txt` files).

Hi Again, 

this is the detailed error I am stuck at:

Found Thorlabs TSI camera serial=08126
Traceback (most recent call last):
  File "E:\ASHIQ\TEST\pyLabLib-cam-control-2.2.1\pylablib\devices\utils\load_lib.py", line 264, in temp_open
    yield init_result,open_result
  File "E:\ASHIQ\TEST\pyLabLib-cam-control-2.2.1\pylablib\devices\Thorlabs\TLCamera.py", line 91, in open
    self._tsclk=self.get_timestamp_clock_frequency()
  File "E:\ASHIQ\TEST\pyLabLib-cam-control-2.2.1\pylablib\devices\Thorlabs\TLCamera.py", line 252, in get_timestamp_clock_frequency
    return lib.tl_camera_get_timestamp_clock_frequency(self.handle) or None
  File "<string>", line 1, in <lambda>
  File "E:\ASHIQ\TEST\pyLabLib-cam-control-2.2.1\pylablib\core\utils\ctypes_wrap.py", line 279, in wrapped_func
    retval=func(*call_args)
  File "E:\ASHIQ\TEST\pyLabLib-cam-control-2.2.1\pylablib\devices\Thorlabs\tl_camera_sdk_lib.py", line 42, in errchecker
    raise ThorlabsTLCameraLibError(func.__name__,result,lib=lib)
pylablib.devices.Thorlabs.tl_camera_sdk_lib.ThorlabsTLCameraLibError: function 'tl_camera_get_timestamp_clock_frequency' raised error 1004(UNKNOWN): Condition is unexpectedly false: Pointer(s) for receiving the value(s) must be provided. Error: Invalid operation.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\ASHIQ\TEST\pyLabLib-cam-control-2.2.1\utils\cameras\ThorlabsTLCam.py", line 37, in iterate_cameras
    with Thorlabs.ThorlabsTLCamera(serial) as cam:
  File "E:\ASHIQ\TEST\pyLabLib-cam-control-2.2.1\pylablib\devices\Thorlabs\TLCamera.py", line 68, in __init__
    self.open()
  File "E:\ASHIQ\TEST\pyLabLib-cam-control-2.2.1\pylablib\devices\Thorlabs\TLCamera.py", line 92, in open
    self._opid=libctl.open().opid
  File "E:\Anaconda\envs\python-camra\lib\contextlib.py", line 99, in __exit__
    self.gen.throw(type, value, traceback)
  File "E:\ASHIQ\TEST\pyLabLib-cam-control-2.2.1\pylablib\devices\utils\load_lib.py", line 266, in temp_open
    self.close(opid)
  File "E:\ASHIQ\TEST\pyLabLib-cam-control-2.2.1\pylablib\devices\utils\load_lib.py", line 256, in close
    uninit_result=self._do_uninit() # pylint: disable=assignment-from-no-return
  File "E:\ASHIQ\TEST\pyLabLib-cam-control-2.2.1\pylablib\devices\Thorlabs\TLCamera.py", line 28, in _do_uninit
    lib.tl_camera_close_sdk()
  File "<string>", line 1, in <lambda>
  File "E:\ASHIQ\TEST\pyLabLib-cam-control-2.2.1\pylablib\core\utils\ctypes_wrap.py", line 279, in wrapped_func
    retval=func(*call_args)
  File "E:\ASHIQ\TEST\pyLabLib-cam-control-2.2.1\pylablib\devices\Thorlabs\tl_camera_sdk_lib.py", line 42, in errchecker
    raise ThorlabsTLCameraLibError(func.__name__,result,lib=lib)
pylablib.devices.Thorlabs.tl_camera_sdk_lib.ThorlabsTLCameraLibError: function 'tl_camera_close_sdk' raised error 1004(UNKNOWN): Condition is unexpectedly false: Cameras must be closed before closing the SDK. Error: Invalid operation.

**Comment by AlexShkarin** [comment]
Thanks for the info! There seems to be a problem with some Thorlabs cameras and/or software version not supporting the ``tl_camera_get_timestamp_clock_frequency`` method. This should be fixed in the new version of the pylablib package, but there's not corresponding version of cam-control yet, so you will need to update pylablib in your version of cam-control.

If you're using cam-control directly from source (e.g., you've downloaded the source code from the GitHub repository), you can simply update your version of pylablib (or pylablib-lightweight) to 1.4.2: ``python -m pip install -U pylablib``. If you're running the standalone application which comes with its own python interpreter (the one you download as a large zip file), you need to do a couple of steps:

- First, you should go to the ``python`` folder inside the outer-most ``cam-control`` folder (the one that also contains ``control.exe`` and in there run ``local-python.bat``, which should open a command line.
- There you need to run ``python -m pip install -U pylablib-lightweight``, which will install the most recent pylablib version.
- Finally, you need to delete the ``pylablib`` folder inside the inner ``cam-control`` folder (the one with ``control.py``, ``logout.txt``, etc.) to make it use the newly installed version.

Let me know if that helps.

**Comment by zamanashiq3** [comment]
Turns out it was the issue with Thorlabs Camera Drivers. This works flawlessly with IDS uEye. Thanks.
